kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeployments
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mydeployments
  template:
    metadata:
      labels:
        name: mydeployments
    spec:
      containers:
        - name: c00
          image: httpd
          ports:
            - containerPort: 80

