kind: Pod
apiVersion: v1
metadata:
   name: mypod
spec:
   containers:
     - name: c01
       image: centos
       command: ["/bin/bash", "-c", "while true; do echo 'container c1 is running'; sleep 10; done"]
       volumeMounts:
          - name: podvol
            mountPath: "/tmp/c1dir"

     - name: c02
       image: centos
       command: ["/bin/bash", "-c", "while true; do echo 'container c2 is running'; sleep 20; done"]
       volumeMounts:
          - name: podvol
            mountPath: "/tmp/c3dir"
   volumes:
      - name: podvol
        hostPath:
           path: "/tmp/hostdir" 
