kind: Pod
apiVersion: v1
metadata:
    name: testpod1
spec:
   containers:
     - name: c00
       image: ubuntu
       command: ["/bin/bash","-c","while true; do echo 'c01 is running'; sleep 5; done"]
