kind: Pod
apiVersion: v1
metadata:
 name: labelpod2
 labels:
     day: sat
     class: kubernetes
spec:
  containers:
  - name: c01
    image: ubuntu
    command: ["/bin/bash","-c","while true; do echo Hello-Sai!; sleep 5; done"]
