kind: ReplicaSet
apiVersion: apps/v1
metadata:
   name: replicasettestpod
spec:
   replicas: 2
   selector:
      matchExpressions:
        - key: myname
          operator: In
          values: [hari,sai,raj]
   template:
     metadata:
        labels:
           myname: raj
     spec:
       containers:
         - name: c00
           image: ubuntu
           command: ["/bin/bash","-c","while true; do echo hello world!; sleep 5; done"]
